# MacBridge — build entry points.
# Copyright © 2026 Todd Dube. Licensed under the MIT License; see LICENSE.
#
# Two build systems, on purpose:
#   * SwiftPM  — MacBridgeKit, the CLI and the tests. Fast, terminal-friendly, CI-friendly.
#   * Xcode    — the .app bundle, Info.plist, entitlements and code signing, which
#                SwiftPM cannot produce. Generated from project.yml by xcodegen.
#
# SCRATCH and DERIVED live outside the repo on purpose. This checkout sits under an
# iCloud-synced ~/Documents, which stamps com.apple.FinderInfo on build output;
# codesign then refuses the bundle with "resource fork, Finder information, or
# similar detritus not allowed". Building elsewhere avoids it entirely.
SCRATCH  ?= /private/tmp/macbridge-build
DERIVED  ?= /private/tmp/macbridge-dd
CONFIG   ?= Release

# Tests and the app need Xcode's toolchain: swift-testing's macro plugin,
# Testing.framework and xcodebuild all ship only with Xcode, not Command Line
# Tools. Prefers a release Xcode, falls back to a beta.
XCODE_DEV := $(firstword $(wildcard /Applications/Xcode.app/Contents/Developer \
                                    /Applications/Xcode-beta.app/Contents/Developer))
XCSWIFT    = $(XCODE_DEV)/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
XCBUILD    = $(XCODE_DEV)/usr/bin/xcodebuild

CLI     = $(SCRATCH)/debug/macbridge
APP     = $(DERIVED)/Build/Products/$(CONFIG)/MacBridge.app
APP_CLI = $(APP)/Contents/MacOS/macbridge

.PHONY: help build test icons signing project app install run stop doctor tools verify release publish clean

help:
	@echo "MacBridge targets:"
	@echo "  make build     SwiftPM build of MacBridgeKit + the macbridge CLI"
	@echo "  make test      Run the test suite (needs Xcode)"
	@echo "  make project   Regenerate MacBridge.xcodeproj from project.yml"
	@echo "  make icons     Redraw the app icon"
	@echo "  make signing   Detect a signing identity and write Signing.xcconfig"
	@echo "  make app       Build MacBridge.app ($(CONFIG))"
	@echo "  make install   Build and install to /Applications, then launch"
	@echo "  make run       Launch the installed app"
	@echo "  make stop      Quit the running app"
	@echo "  make doctor    Permissions, bridge status and tool inventory"
	@echo "  make tools     List the tools"
	@echo "  make verify    Live round-trip on a disposable list (needs permissions)"
	@echo "  make release   Build, sign, notarize and staple MacBridge-<version>.dmg"
	@echo "  make publish   Upload that DMG as a draft GitHub release (needs gh)"
	@echo "  make clean     Remove build directories"
	@echo ""
	@echo "Xcode:     $(if $(XCODE_DEV),$(XCODE_DEV),NOT FOUND — install Xcode for test/app/install)"

build:
	swift build --scratch-path $(SCRATCH)

test:
	@test -n "$(XCODE_DEV)" || { echo "Xcode is required for tests (swift-testing ships with Xcode, not CLT)."; exit 1; }
	DEVELOPER_DIR=$(XCODE_DEV) $(XCSWIFT) test --scratch-path $(SCRATCH)

# Redraw the app icon into App/Assets.xcassets.
# The artwork is code (Tools/generate-icons.swift), so edit that and re-run.
icons:
	swift Tools/generate-icons.swift

# Detect a code-signing identity and write Signing.xcconfig.
#
# Prefers a Developer ID (distributable), then Apple Development, else ad-hoc. The
# certificate is referenced by SHA-1 hash, not by name: Xcode's manual signing
# resolves the name "Apple Development" to a *Mac* Development certificate and fails
# when no account matches the team, whereas the hash is used directly. That failure
# is why this exists.
signing:
	@pick() { security find-identity -v -p codesigning 2>/dev/null | grep "\"$$1" | head -1; }; \
	line=$$(pick "Developer ID Application"); \
	[ -n "$$line" ] || line=$$(pick "Apple Development"); \
	identity=$$(echo "$$line" | awk '{print $$2}'); \
	name=$$(echo "$$line" | sed -E 's/.*"(.*)".*/\1/'); \
	{ \
		echo "// GENERATED by 'make signing' — do not edit, do not commit."; \
		echo "// Machine-local signing; see the configFiles note in project.yml."; \
		echo "CODE_SIGN_STYLE = Manual"; \
		echo "DEVELOPMENT_TEAM ="; \
		echo "PROVISIONING_PROFILE_SPECIFIER ="; \
		if [ -n "$$identity" ]; then \
			echo "CODE_SIGN_IDENTITY = $$identity"; \
		else \
			echo "CODE_SIGN_IDENTITY = -"; \
		fi; \
	} > Signing.xcconfig; \
	if [ -n "$$identity" ]; then \
		echo "signing as: $$name"; \
		echo "  TCC grants will survive rebuilds."; \
	else \
		echo "signing: ad-hoc (no Developer ID or Apple Development certificate found)"; \
		echo "  NOTE: an ad-hoc signature changes every rebuild, so macOS revokes"; \
		echo "  Calendar and Reminders on each install. Re-grant from the panel."; \
	fi

# project.yml is the source of truth for targets, build settings AND Info.plist.
# App/Info.plist is generated — editing it by hand is pointless, this overwrites it.
project: signing
	@command -v xcodegen >/dev/null || { echo "xcodegen not found: brew install xcodegen"; exit 1; }
	DEVELOPER_DIR=$(XCODE_DEV) xcodegen generate

app: project
	@test -n "$(XCODE_DEV)" || { echo "Xcode is required to build the app bundle."; exit 1; }
	DEVELOPER_DIR=$(XCODE_DEV) $(XCBUILD) -project MacBridge.xcodeproj -scheme MacBridge \
		-configuration $(CONFIG) -derivedDataPath $(DERIVED) build

# TCC ties a grant to the app's identity and location, so the app has to live at a
# stable path to keep its Calendar and Reminders permissions across rebuilds.
install: stop app
	rm -rf /Applications/MacBridge.app
	cp -R "$(APP)" /Applications/
	codesign -v /Applications/MacBridge.app && echo "signature ok"
	@codesign -dv /Applications/MacBridge.app 2>&1 | grep -q adhoc \
		&& echo "  signed ad-hoc: re-grant Calendar and Reminders after each install" \
		|| echo "  signed with a stable identity: permission grants persist"
	open /Applications/MacBridge.app
	@echo "Installed. Grant Calendar and Reminders access from the menu-bar panel."

run:
	open /Applications/MacBridge.app

# Anchored on purpose. Without the $, this pattern also matches
# ".../macbridge mcp" — every connected client's shim — so installing tore down
# their MCP servers and Claude logged "Server disconnected". Only the GUI app,
# which runs with no arguments, should be stopped here.
stop:
	-pkill -x -f "/Applications/MacBridge.app/Contents/MacOS/macbridge" 2>/dev/null || true

doctor: build
	$(CLI) doctor

tools: build
	$(CLI) tools

# Live round-trip against real EventKit data, on a list it creates and deletes.
# Needs Calendar and Reminders permission for whatever runs it.
verify:
	@test -n "$(XCODE_DEV)" || { echo "Xcode is required for tests."; exit 1; }
	MACBRIDGE_LIVE=1 DEVELOPER_DIR=$(XCODE_DEV) $(XCSWIFT) test --scratch-path $(SCRATCH)

# Build the download for people who won't build from source: a signed, notarized
# and stapled disk image with the app and an Applications shortcut to drag it onto.
#
# Prerequisites, both account setup rather than code (paid Apple Developer Program):
#   1. A "Developer ID Application" certificate: Xcode → Settings → Accounts →
#      Manage Certificates → + → Developer ID Application. `make signing` prefers
#      it automatically once it exists.
#   2. Stored notary credentials, once per Mac:
#      xcrun notarytool store-credentials macbridge-notary \
#        --apple-id <your-apple-id> --team-id <TEAMID> --password <app-specific-password>
#      (an app-specific password from account.apple.com → Sign-In and Security).
#
# Checks both first and explains, rather than failing deep inside notarytool. The
# disk image is notarized as a whole, which covers the app inside it, and the
# ticket is stapled to the image so the first launch works offline.
#
# The app is re-signed here rather than trusted as Xcode left it: a plain build
# signs with --timestamp=none, and notarization rejects a signature without a
# secure timestamp, but only after the upload. Building also refreshes the copy in
# /Applications (the scheme's post-build step), as `make install` does.
NOTARY_PROFILE ?= macbridge-notary
DIST    ?= /private/tmp/macbridge-dist
VERSION := $(shell awk '/MARKETING_VERSION:/ {gsub(/"/, "", $$2); print $$2}' project.yml)
DMG      = $(DIST)/MacBridge-$(VERSION).dmg

release: test app
	@codesign -dvv "$(APP)" 2>&1 | grep -q "Authority=Developer ID Application" || { \
		echo "Cannot release: the app is not signed with a Developer ID Application certificate."; \
		echo "  Currently signed by: $$(codesign -dvv "$(APP)" 2>&1 | awk -F'=' '/^Authority=/{print $$2; exit}')"; \
		echo "  Create one in Xcode → Settings → Accounts → Manage Certificates → +,"; \
		echo "  then re-run 'make release' (it re-detects signing)."; \
		exit 1; \
	}
	@xcrun notarytool history --keychain-profile $(NOTARY_PROFILE) >/dev/null 2>&1 || { \
		echo "Cannot release: no stored notary credentials for profile '$(NOTARY_PROFILE)'."; \
		echo "  xcrun notarytool store-credentials $(NOTARY_PROFILE) \\"; \
		echo "    --apple-id <apple-id> --team-id <TEAMID> --password <app-specific-password>"; \
		exit 1; \
	}
	@codesign -d --entitlements - "$(APP)" 2>/dev/null | grep -q get-task-allow && { \
		echo "Cannot release: get-task-allow is present. Build Release, not Debug."; exit 1; \
	} || true
	rm -rf $(DIST) && mkdir -p $(DIST)/stage
	ditto "$(APP)" $(DIST)/stage/MacBridge.app
	codesign --force --sign "$$(awk -F' = ' '/^CODE_SIGN_IDENTITY/{print $$2}' Signing.xcconfig)" \
		--options runtime --timestamp --entitlements App/MacBridge.entitlements \
		$(DIST)/stage/MacBridge.app
	@codesign -dvv $(DIST)/stage/MacBridge.app 2>&1 | grep -q '^Timestamp=' || { \
		echo "Cannot release: the signature has no secure timestamp (is the network up?)."; exit 1; }
	ln -s /Applications $(DIST)/stage/Applications
	hdiutil create -volname "MacBridge $(VERSION)" -srcfolder $(DIST)/stage \
		-fs HFS+ -format UDZO -ov "$(DMG)"
	codesign --sign "$$(awk -F' = ' '/^CODE_SIGN_IDENTITY/{print $$2}' Signing.xcconfig)" --timestamp "$(DMG)"
	xcrun notarytool submit "$(DMG)" --keychain-profile $(NOTARY_PROFILE) --wait
	xcrun stapler staple "$(DMG)"
	spctl --assess --type open --context context:primary-signature --verbose "$(DMG)"
	@cd $(DIST) && shasum -a 256 MacBridge-$(VERSION).dmg | tee MacBridge-$(VERSION).dmg.sha256
	@git rev-parse HEAD > $(DIST)/commit
	@echo "Ready: $(DMG). Run 'make publish' to upload it as a draft GitHub release."

# Upload the DMG from 'make release' as a DRAFT release tagged v<version>, so the
# notes can be reviewed on GitHub before anyone can download it.
publish:
	@test -f "$(DMG)" || { echo "No $(DMG). Run 'make release' first."; exit 1; }
	@command -v gh >/dev/null || { echo "gh not found: brew install gh"; exit 1; }
	@test -z "$$(git status --porcelain)" || { echo "Commit your changes first: the tag must match the build."; exit 1; }
	@test "$$(cat $(DIST)/commit 2>/dev/null)" = "$$(git rev-parse HEAD)" || { \
		echo "The DMG was built from a different commit. Run 'make release' again."; exit 1; }
	git push origin HEAD
	gh release create "v$(VERSION)" "$(DMG)" "$(DMG).sha256" --draft --target "$$(git rev-parse HEAD)" \
		--title "MacBridge $(VERSION)" --generate-notes
	@echo "Draft created. Review and publish it at: $$(gh repo view --json url -q .url)/releases"

clean:
	rm -rf $(SCRATCH) $(DERIVED)
