#!/usr/bin/env python3
# mac-bridge — Morning Briefing Agent
# Runs: 7:00 AM daily via launchd

"""
Daily morning briefing — Claude API with mac-bridge tool calling.

Claude autonomously calls calendar, reminder, and mail tools,
then produces an HTML briefing email + short iMessage push.

Run manually:
    uv run --extra agent agents/morning_briefing.py
    uv run --extra agent agents/morning_briefing.py --dry-run
"""

import argparse
import asyncio
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.runner import (
    EMAIL_RECIPIENT,
    extract_sections,
    run_agent,
    send_html_email,
    send_imessage_via_mcp,
    setup_logging,
)

TODAY = date.today()
END = TODAY + timedelta(days=7)

SYSTEM = f"""\
You are a sharp personal chief of staff generating a daily briefing email for Todd Dube.

## Your task
Use the available mac-bridge tools to gather data, then produce the briefing.

### Data to collect (call these tools):
1. get_calendar_events — start_date="{TODAY.isoformat()}", end_date="{END.isoformat()}", limit=100
2. get_overdue_reminders — limit=50
3. get_upcoming_reminders — days=7, limit=50
4. get_unread_emails — count=20

### Output format (use exactly these tags):
<html>
[Complete HTML briefing email body — inline CSS only, no html/head/body wrappers]
</html>

<imessage>
[Under 200 chars: today's event count, top 1-2 urgent items or overdue count. Be specific.]
</imessage>

## HTML Design Specification

### Color palette:
- Header bg: #1a3a5c (dark navy)
- Today accent: #1a73e8 (blue)
- This Week: border #0f5132, bg #d1e7dd
- Overdue: border #842029, bg #f8d7da
- Upcoming: border #664d03, bg #fff3cd
- Email Follow-up: border #4a1d96, bg #ede9fe
- Divider: #dee2e6 | Body text: #212529 | Muted: #6c757d
- HIGH badge: bg #dc3545 white | MEDIUM: bg #fd7e14 white | LOW: bg #ffc107 #212529

### Card style:
border-radius:8px; border:1px solid #dee2e6; margin-bottom:20px; overflow:hidden
Card header: padding:12px 16px; font-weight:bold; font-size:15px
Data rows: padding:10px 16px; border-top:1px solid #dee2e6
All font-family: Arial, Helvetica, sans-serif

### Sections (in order):
1. **Header** — navy bar: "Daily Briefing" h1 in white + date in #93b8d8
2. **Today's Schedule** — blue accent; TIME | EVENT | CALENDAR table; conflict rows in #fff3cd bg
3. **This Week** — green accent; group by day with bold day header rows
4. **Overdue Reminders** — red accent; count badge; priority badge | title | list | days overdue
5. **Due This Week** — amber accent; count badge; group by date; priority badge | title | list
6. **Email Follow-up** — purple accent; sender (bold, 24 chars max) | subject | received time
   Flag time-sensitive subjects (urgent/deadline/invoice/payment/action required) with red "!" badge
7. **Footer** — muted centered: "Generated by mac-bridge · {TODAY.isoformat()}"

### Rules:
- "Nothing scheduled" / "Nothing overdue" / "Nothing due" placeholders — never omit a section
- Overlapping calendar events: highlight row with background #fff3cd, left border 4px solid #ffc107
- Priority sort: high → medium → low → none
- All-day events: show "All Day" in muted grey in the TIME column
- Omit Email Follow-up section entirely if no email data
- Use <table> for layout (not flexbox/grid — email compatibility)
- Return ONLY the HTML body fragment inside the <html> tags
"""

TASK = f"Today is {TODAY.strftime('%A, %B %-d, %Y')}. Generate my daily briefing."


async def main(dry_run: bool = False) -> None:
    log = setup_logging("morning_briefing", dry_run)
    log.info("Starting morning briefing (dry_run=%s)", dry_run)

    output = await run_agent(TASK, SYSTEM, model="claude-haiku-4-5-20251001", max_tokens=8000, log=log)
    html, imessage = extract_sections(output)

    if not html.strip():
        log.error("Claude returned empty HTML — check logs")
        return

    subject = f"Daily Briefing — {TODAY.strftime('%A, %B %-d')}"

    if dry_run:
        print(f"\n{'='*60}")
        print("HTML PREVIEW (first 800 chars)")
        print('='*60)
        print(html[:800] + ("..." if len(html) > 800 else ""))
        print(f"\n{'='*60}")
        print("IMESSAGE PREVIEW")
        print('='*60)
        print(imessage or "(no iMessage generated)")
        return

    send_html_email(html, subject, log=log)

    if imessage:
        await send_imessage_via_mcp(imessage, log=log)
    else:
        log.warning("No iMessage text extracted from Claude output")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Morning briefing agent")
    parser.add_argument("--dry-run", action="store_true", help="Print preview, do not send")
    args = parser.parse_args()
    asyncio.run(main(args.dry_run))
