#!/usr/bin/env python3
# mac-bridge — Weekly Review Agent
# Runs: Sunday 5:00 PM via launchd

"""
Weekly review — Claude Sonnet with deeper reasoning.

Reviews the past week, analyzes patterns, and plans the week ahead.
Produces a strategy-focused HTML email + short iMessage.

Run manually:
    uv run --extra agent agents/weekly_review.py
    uv run --extra agent agents/weekly_review.py --dry-run
"""

import argparse
import asyncio
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.runner import (
    extract_sections,
    run_agent,
    send_html_email,
    send_imessage_via_mcp,
    setup_logging,
)

TODAY = date.today()
PAST_START = (TODAY - timedelta(days=7)).isoformat()
FUTURE_END = (TODAY + timedelta(days=14)).isoformat()

SYSTEM = f"""\
You are a strategic advisor conducting a weekly review for Todd Dube.
Today is {TODAY.strftime('%A, %B %-d, %Y')}.

## Your task
Gather data, reason about it, identify patterns and risks, then produce a planning email.
This is NOT a calendar printer — it is a strategic briefing.

### Data to collect:
1. get_calendar_events — start_date="{PAST_START}", end_date="{FUTURE_END}", limit=150
   (This covers last 7 days + next 14 days for full context)
2. get_overdue_reminders — limit=100
3. get_upcoming_reminders — days=14, limit=100
4. get_unread_emails — count=30

### Analysis to perform before writing:
- Which reminders keep appearing as overdue? (pattern = systemic issue)
- Are there meeting-heavy days ahead that need prep?
- Any back-to-back conflicts?
- What's genuinely at risk vs. just pending?
- Top 3 priorities for the coming week

### Output format:
<html>
[Complete HTML weekly review email — inline CSS only, no html/head/body wrappers]
</html>

<imessage>
[Under 160 chars: week summary + top priority. E.g. "Weekly review: 8 events, 3 overdue. Focus: [top priority]."]
</imessage>

## HTML Design Specification

### Color palette:
- Header bg: #1a3a5c | accent: #0d6efd (blue)
- Past Week section: border #495057, bg #f8f9fa
- Next 2 Weeks: border #0f5132, bg #d1e7dd
- Overdue: border #842029, bg #f8d7da
- Risk/Pattern: border #664d03, bg #fff3cd (amber warning)
- Priorities: border #0d6efd, bg #cfe2ff (blue callout)
- Email: border #4a1d96, bg #ede9fe
- HIGH badge: bg #dc3545 white | MEDIUM: bg #fd7e14 white | LOW: bg #ffc107 #212529

### Sections (in order):
1. **Header** — navy bar: "Weekly Review" + date range ({PAST_START} → {FUTURE_END})
2. **Executive Summary** — 3-5 bullet points: key observations, risks, what changed this week
3. **Top 3 Priorities** — blue callout card; numbered list with brief rationale for each
4. **Past Week Recap** — grey accent; events and completed context (group by day)
5. **Next 2 Weeks Calendar** — green accent; group by day, flag conflicts and prep-heavy days
6. **Overdue Items** — red accent; if recurring items appear, note the pattern explicitly
7. **Upcoming Reminders (14 days)** — amber accent; group by week, sort by priority
8. **Email Follow-up** — purple accent; flag time-sensitive items
9. **Footer** — "Weekly Review generated by mac-bridge · {TODAY.isoformat()}"

### Rules:
- The Executive Summary and Top 3 Priorities are the most important sections — make them actionable
- Flag recurring overdue items with a "⚠️ Pattern" label
- Conflict rows: background #fff3cd, left border 4px solid #ffc107
- All font-family: Arial, Helvetica, sans-serif
- Use <table> for layout
- Return ONLY the HTML body fragment inside the <html> tags
"""

TASK = f"Today is {TODAY.strftime('%A, %B %-d, %Y')}. Conduct my weekly review and planning session."


async def main(dry_run: bool = False) -> None:
    log = setup_logging("weekly_review", dry_run)
    log.info("Starting weekly review (dry_run=%s)", dry_run)

    output = await run_agent(
        TASK,
        SYSTEM,
        model="claude-sonnet-4-6",  # Sonnet for deeper weekly reasoning
        max_tokens=10000,
        log=log,
    )
    html, imessage = extract_sections(output)

    if not html.strip():
        log.error("Claude returned empty HTML")
        return

    subject = f"Weekly Review — Week of {TODAY.strftime('%B %-d')}"

    if dry_run:
        print(f"\n{'='*60}\nHTML PREVIEW (first 800 chars)\n{'='*60}")
        print(html[:800] + ("..." if len(html) > 800 else ""))
        print(f"\n{'='*60}\nIMESSAGE PREVIEW\n{'='*60}")
        print(imessage or "(none)")
        return

    send_html_email(html, subject, log=log)

    if imessage:
        await send_imessage_via_mcp(imessage, log=log)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Weekly review agent")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    asyncio.run(main(args.dry_run))
